RESTART/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

#로그인 로그아웃 매핑부

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),

]

RESTART/config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),#인클루드 해서 저어기 파이보에 있는 urls파일로 가라고 한것
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),#/이 눌리면 이동할 경로

]

RESTART/pybo/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views, comment_views, vote_views


app_name = 'pybo'#url관리하는 너를 pybo라는 이름으로 부를꺼야.


urlpatterns = [
    #질문 추천에 있는것들
    path('vote/question/<int:question_id>/', vote_views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/', vote_views.vote_answer, name='vote_answer'),


    #베이스에 있는것들
    path('', base_views.index, name='index'),
    path('<int:question_id>/', base_views.detail, name='detail'),#네임은 url에 이름지어준것, html에서 이름 부르면 얘로 연결됨, 얘한테 필요한 값(id)필수
    
    #퀘스천에 있는것들
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),

    #답변에 있는것들
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),
    
    #댓글에 있는것들
    path('comment/create/question/<int:question_id>/', comment_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/', comment_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/', comment_views.comment_delete_question, name='comment_delete_question'),

    #comment_views(대댓글기능)
    path('comment/create/answer/<int:answer_id>/', comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_answer, name='comment_delete_answer'),

]

RESTART/pybo/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from ..models import Question
from django.db.models import Q, Count



def index(request):
  """
  pybo 목록 출력
  """

  #입력인자
  page = request.GET.get('page','1') #페이지
  kw = request.GET.get('kw','') #검색어
  so = request.GET.get('so','recent') #정렬기준

  
  #정렬
  if so == 'recommend':
    question_list = Question.objects.annotate(
      num_voter=Count('voter')).order_by('-num_voter','-create_date')
  elif so == 'popular':
    question_list = Question.objects.annotate(
      num_answer=Count('answer')).order_by('-num_answer', '-create_date')
  else: #recent
      question_list = Question.objects.order_by('-create_date')
  
  
  #조회
  #question_list = Question.objects.order_by('-create_date')#앞에 - 가 붙어있어서 작성일시 역순으로 보여준다. order_by조회한 데이터를 특정 속성으로 정렬
  if kw:
    question_list = question_list.filter(
      Q(subject__icontains=kw) | #제목검색
      Q(content__icontains=kw) | #내용 검색
      Q(author__username__icontains=kw) | #질문 글쓴이 검색
      Q(answer__author__username__icontains=kw) # 답변 글쓴이 검색
    ).distinct()

  #페이징 처리
  paginator = Paginator(question_list, 10) #페이지당 10개씩 보여주기
  page_obj = paginator.get_page(page) #페이징 구형에 사용한 클래스에서, 요청한 페이지값을 가져온다.
  
  context = {'question_list':page_obj, 'page':page, 'kw':kw, 'so':so}
  #return HttpResponse("pybo에 오신것을 환영합니다.")
  return render(request, 'pybo/question_list.html', context)


def detail(request, question_id):
  """
  pybo 내용 출력
  """
  #question = Question.objects.get(id = question_id)
  question = get_object_or_404(Question, pk = question_id)
  context = {'question':question}
  return render(request, 'pybo/question_detail.html', context)

RESTART/templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
    <head>
        <!-- Requirde meta tags -->
        <meta charset="utf-8">
        
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- <meta name="viewport" content="width=devic-width, initial-scale1, shrink-to-fit=no"> -->
        
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
        <!-- pybo CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
        <title> Hello, pybo!</title>
    </head>
    <body>
        {% include "navbar.html" %}
        <!-- 기본 템플릿 안에 삽입될 내용 시작! -->
        {% block content %}
        {% endblock %}
        <!-- 기본 템플릿 안에 삽입될 내용 끝! -->
        <!-- jQuery JS -->
        <script src = "{% static 'jquery-3.4.1.min.js' %}"></script>
        <!-- Bootstrap JS -->
        <script src="{% static 'bootstrap.min.js' %}"></script>
        <!-- 자바스크립트 Start -->
        {% block script %}
        {% endblock %}
        <!-- 자바스크립트 End -->
    </body>
</html>

RESTART/templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}<!--필드오류를 출력한다-->
            <div class="alert alert-danger">
                <strong>
                    {{ field.label }}
                </strong>
                {{error}}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}<!--넌 필드 에러 출력부-->
        <div class="alert alert-danger">
            <strong>
                {{ error }}
            </strong>
        </div>
    {% endfor %}
{% endif %}
        

RESTART/templates/navbar.html
<!-- 네비게이션 바! -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navber-brand" href="{% url 'pybo:index' %}">
        pybo
    </a>
    <button class="navbar-toggler ml-auto" type="button" data-toggler="collapse" data-target="#navbarNav" 
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation" onclick="test()" id="test">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:logout' %}">
                        {{ user.username }} (로그아웃)
                    </a>
                {% else %}
                    <a class="nav-link" href="{% url 'common:login' %}">
                        로그인
                    </a>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>

<script>

function test(){
    var test = $("#test").val()
    console.log(test)
}

</script>