RESTART/config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),#인클루드 해서 저어기 파이보에 있는 urls파일로 가라고 한것
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),#/이 눌리면 이동할 경로

]

RESTART/pybo/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views, comment_views, vote_views


app_name = 'pybo'#url관리하는 너를 pybo라는 이름으로 부를꺼야.


urlpatterns = [
    #질문 추천에 있는것들
    path('vote/question/<int:question_id>/', vote_views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/', vote_views.vote_answer, name='vote_answer'),


    #베이스에 있는것들
    path('', base_views.index, name='index'),
    path('<int:question_id>/', base_views.detail, name='detail'),#네임은 url에 이름지어준것, html에서 이름 부르면 얘로 연결됨, 얘한테 필요한 값(id)필수
    
    #퀘스천에 있는것들
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),

    #답변에 있는것들
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),
    
    #댓글에 있는것들
    path('comment/create/question/<int:question_id>/', comment_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/', comment_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/', comment_views.comment_delete_question, name='comment_delete_question'),

    #comment_views(대댓글기능)
    path('comment/create/answer/<int:answer_id>/', comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_answer, name='comment_delete_answer'),

]

RESTART/pybo/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question')
    subject = models.CharField(max_length = 200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True,blank=True)
    voter = models.ManyToManyField(User, related_name='voter_question') #오, 이거 부트할때 본것같은데? 

    def __str__(self):
        return self.subject#서브젝 = 제목. 얘가 있어야. 등록된 id가 아닌 제목을 표시해준다.


class Answer(models.Model):
    author = models.ForeignKey(User,on_delete=models.CASCADE, related_name='author_answer')
    question = models.ForeignKey(Question, on_delete = models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True,blank=True)
    voter = models.ManyToManyField(User, related_name='voter_answer') #부트에서 봤던 JPA형식이랑 비슷하다.

class Comment(models.Model):
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True,blank=True)
    question = models.ForeignKey(Question, null=True, blank=True, on_delete = models.CASCADE)
    answer = models.ForeignKey(Answer, null=True, blank=True, on_delete = models.CASCADE)

RESTART/pybo/forms.py
from django import forms
from pybo.models import Question, Answer, Comment


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content']
        labels = {
            'subject' : '제목',
            'content' : '내용',
        }




class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content' : '답변내용',
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {
            'content' : '댓글내용',
        }

RESTART/pybo/views/answer_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone

from ..models import Question, Answer
from ..forms import AnswerForm


@login_required(login_url='common:login')
def answer_create(request, question_id):
    """
    pybo 답변등록
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.create_date = timezone.now()
            answer.question=question
            answer.save()
            return redirect('{}#answer_{}'.format(resolve_url('pybo:detail', question_id=question.id), answer.id))
        else :
            form = AnswerForm()
        context = {'question':question, 'form':form}
        return render(request, 'ptbo/question_detail.html', context)


@login_required(login_url='common:login')#작성아이디와 실행아이디가 같아야만 작동
def answer_modify(request, answer_id):
    """
    pybo 답변 수정
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '수정권한이 없습니다.')
        return redirect('pybo:detail', question_id=answer.question.id)

    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('{}#answer_{}'.format(resolve_url('pybo:detail', question_id = answer.question.id), answer.id))
    else:
        form = AnswerForm(instance = answer)
    context = {'answer':answer, 'form':form}
    return render(request, 'pybo/answer_form.html', context)


@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    """
    pybo 답변삭제
    """
    answer = get_object_or_404(Answer, pk = answer_id)
    print(request.user,answer.author)
    if request.user != answer.author:
        messages.error(request, '삭제권한이 없습니다.')
    else:
        answer.delete()
    return redirect('pybo:detail', question_id = answer.question.id)
    

RESTART/pybo/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from ..models import Question
from django.db.models import Q, Count



def index(request):
  """
  pybo 목록 출력
  """

  #입력인자
  page = request.GET.get('page','1') #페이지
  kw = request.GET.get('kw','') #검색어
  so = request.GET.get('so','recent') #정렬기준

  
  #정렬
  if so == 'recommend':
    question_list = Question.objects.annotate(
      num_voter=Count('voter')).order_by('-num_voter','-create_date')
  elif so == 'popular':
    question_list = Question.objects.annotate(
      num_answer=Count('answer')).order_by('-num_answer', '-create_date')
  else: #recent
      question_list = Question.objects.order_by('-create_date')
  
  
  #조회
  #question_list = Question.objects.order_by('-create_date')#앞에 - 가 붙어있어서 작성일시 역순으로 보여준다. order_by조회한 데이터를 특정 속성으로 정렬
  if kw:
    question_list = question_list.filter(
      Q(subject__icontains=kw) | #제목검색
      Q(content__icontains=kw) | #내용 검색
      Q(author__username__icontains=kw) | #질문 글쓴이 검색
      Q(answer__author__username__icontains=kw) # 답변 글쓴이 검색
    ).distinct()

  #페이징 처리
  paginator = Paginator(question_list, 10) #페이지당 10개씩 보여주기
  page_obj = paginator.get_page(page) #페이징 구형에 사용한 클래스에서, 요청한 페이지값을 가져온다.
  
  context = {'question_list':page_obj, 'page':page, 'kw':kw, 'so':so}
  #return HttpResponse("pybo에 오신것을 환영합니다.")
  return render(request, 'pybo/question_list.html', context)


def detail(request, question_id):
  """
  pybo 내용 출력
  """
  #question = Question.objects.get(id = question_id)
  question = get_object_or_404(Question, pk = question_id)
  context = {'question':question}
  return render(request, 'pybo/question_detail.html', context)

RESTART/pybo/views/comment_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone

from ..models import Question, Answer, Comment
from ..forms import CommentForm



@login_required(login_url='common:login')
def comment_create_question(request, question_id):
    """
    pybo 질문 댓글 등록
    """
    question = get_object_or_404(Question, pk = question_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.question = question #
            comment.save()
            print("comment.question : ",comment)
            return redirect('{}#comment_{}'.format(resolve_url('pybo:detail', question_id=question.id), comment.id))
        
    else :
        form = CommentForm()
    context = {'form' : form}
    return render(request, 'pybo/comment_form.html', context)


@login_required(login_url='common:login')
def comment_modify_question(request, comment_id):
    """
    pybo 질문 댓글 수정
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request,'댓글 수정권한이 없습니다.')
        return redirect('pybo:detail', question_id=comment.question.id)

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.modify_date = timezone.now() #수정일시 저장
            comment.save()
            return redirect('{}#comment_{}'.format(resolve_url('pybo:detail', question_id=comment.question.id), comment.id))
        
    else:
        form = CommentForm(instance = comment)
    context = {'form' : form}
    return render(request, 'pybo/comment_form.html', context)


@login_required(login_url='common:login')
def comment_delete_question(request, comment_id):
    """
    pybo 질문 댓글 삭제
    """
    comment = get_object_or_404(Comment, pk = comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글 삭제권한이 없습니다.')
        return redirect('pybo:detail', question_id = comment.question_id)
    else:
        comment.delete()
    return redirect('pybo:detail', question_id = comment.question_id)


@login_required(login_url='common:login')
def comment_create_answer(request, answer_id):
    """
    pybo 답변 댓글 등록
    """
    answer = get_object_or_404(Answer, pk = answer_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.answer = answer
            comment.save()
            return redirect('{}#comment_{}'.format(resolve_url('pybo:detail', question_id=comment.answer.question.id), comment.id))
        
    else :
        form = CommentForm()
    context = {'form':form}
    return render(request, 'pybo/comment_form.html', context)


@login_required(login_url='common:login')
def comment_modify_answer(request, comment_id):
    """
    pybo 답변 댓글 수정
    """
    comment = get_object_or_404(Comment, pk = comment_id)
    if request.user != comment.author:
        messages.error(request,'댓글 수정권한이 없습니다.')
        return redirect('pybo:detail', question_id=comment.answer.question.id)
    
    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.modify_date = timezone.now()
            comment.save()
            return redirect('{}#comment_{}'.format(resolve_url('pybo:detail', question_id=comment.answer.question.id), comment.id))
        
    else :
        form = CommentForm(instance=comment)
    context = {'form':form}
    return render(request, 'pybo/comment_form.html', context)

@login_required(login_url='common:login')
def comment_delete_answer(request, comment_id):
    """
    pybo 답글 댓글 삭제
    """
    comment = get_object_or_404(Comment, pk = comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글 삭제권한이 없습니다.')
        return redirect('pybo:detail', question_id = comment.answer.question.id)

    else:
        comment.delete()
    return redirect('pybo:detail', question_id = comment.answer.question.id)

RESTART/pybo/views/question_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from ..models import Question
from ..forms import QuestionForm


@login_required(login_url='common:login')
def question_create(request):
    """
    pybo 질문 등록
    """
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.create_date = timezone.now()
            question.save()
            return redirect('pybo:index')
    else :
        form = QuestionForm()#리퀘스트 메소드가 겟 인 경우에만 호출!
    context = {'form':form}
    return render(request, 'pybo/question_form.html', context)


@login_required(login_url='common:login')
def question_modify(request, question_id):
    """
    pybo 질문 수정
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request,'수정권한이 없습니다.')
        return redirect('pybo:detail', question_id=question.id)

    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.modify_date = timezone.now() #수정일시 저장
            question.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = QuestionForm(instance = question)
    context = {'form':form}
    return render(request, 'pybo/question_form.html', context)

@login_required(login_url='common:login')
def question_delete(request, question_id):
    """
    pybo 질문 삭제
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '삭제 권한이 없습니다.')
        return redirect('pybo:detail', question_id=question.id)
    question.delete()
    return redirect('pybo:index')

RESTART/pybo/views/vote_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect

from ..models import Question, Answer


@login_required(login_url='common:login')
def vote_question(request, question_id):
    """
    pybo 질문 추천 등록
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.user == question.author:
        messages.error(request,'본인이 작성한 글은 추천할 수 없습니다.')
    else:
        question.voter.add(request.user)
    return redirect('pybo:detail', question_id=question.id)


@login_required(login_url='common:login')
def vote_answer(request, answer_id):
    """
    pybo 답글 추천 등록
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user == answer.author:
        messages.error(request,'본인이 작성한 글은 추천할 수 없습니다.')
    else:
        answer.voter.add(request.user)
    return redirect('pybo:detail', question_id = answer.question.id)

RESTART/templates/pybo/answer_form.html
{% extends 'base.html' %}

{% block content %}
    <div class="container my-3">
        <form method="post" class="post-form">
            {% csrf_token %}
            {% include "form_errors.html" %}
            <div class="form-group">
                <label for="content">
                    답변내용
                </label>
                <textarea class="form-control" name="content" id="content" rows="10">
                    {{ form.content.value|default_if_none:'' }}
                </textarea>
            </div>
            <button type="submit" class="btn btn-primary">
                저장하기
            </button>
        </form>
    </div>
{% endblock %}

RESTART/templates/pybo/comment_form.html
{% extends 'base.html' %}
{% block content %}
    <div class="container my-3">
        <h5 class="boder-bottom pb-2">
            댓글등록하기
        </h5>
        <form method="post" class="post-form my-3">
            {% csrf_token %}
            {% include "form_errors.html" %}
            <div class="form-group">
                <label for="content">
                    댓글내용
                </label>
                <textarea class="form-control" name="content" id="content" rows="3">
                    {{ form.content.value|default_if_none:'' }}
                </textarea>
            </div>
            <button type="submit" class="btn btn-primary">
                저장하기
            </button>
        </form>
    </div>
{% endblock %}

RESTART/templates/pybo/question_detail.html
{% extends 'base.html' %}
{% load pybo_filter %}
<!--여긴 오류표시하는곳-->
{% block content %}
    <div class="container my-3">
        <!-- 사용자 오류 표시! -->
        {% if messages %}
            <div class="alert alert-danger my-3" role="alert">
                {% for message in messages %}
                    <strong>
                        {{ message.tags }}
                    </strong>
                    <ul>
                        <li>
                            {{ message.message }}
                        </li>
                    </ul>
                {% endfor %}
            </div>
        {% endif %}
        <!-- 사용자 오류 표시 끝! -->
        <h2 class="border-bottom py-2">{{ question.subject }}</h2>
        <!-- 추천 영역 시작! -->
        <div class="row my-3">
            <div class="col-1">
                <div class="bg-light text-center p-3 boder font-weight-bolder mb-1">
                    {{ question.voter.count }}
                </div>
                <a href="#" data-uri="{% url 'pybo:vote_question' question.id %}" class="recommend btn btn-sm btn-block my-1">
                    추천
                </a>
            </div>
            <!-- 추천영역 끝이긴 한데 밑에 꽁다리 두개 추가 -->
            <!-- 질문영역시작! -->
            <div class="col-11">
                <div class="card my-3">
                    <div class="card-body">
                        <div class="card-text" style="width-space: pre-line;">
                            {{ question.content|mark }}
                        </div>
                        <div class="d-flex justify-content-end">
                            <!--수정일시(질문) 표시 추가 시작-->
                            {% if question.modify_date %}
                                <div class="badge badge-light p-2 text-left mx-3">
                                    <div class="mb-2">
                                        modified at
                                    </div>
                                    <div>
                                        {{ question.modify_date }}
                                    </div>
                                </div>
                            {% endif %}
                            <!--수정일시(질문) 표시 추가 끝-->
                            <div class="badge badge-light p-2 text-left">
                                <div class="mb-2">
                                    {{ question.author.username }}
                                </div>
                                <div>
                                    {{ question.create_date }}
                                </div>
                            </div>
                        </div>
                        {% if request.user == question.author %}
                            <div class="my-3">
                                <a href=" {% url 'pybo:question_modify' question.id %}" class="btn btn-sm btn-outline-secondary">
                                    수정
                                </a>
                                <a href="#" class="delete btn btn-sm btn-outline-secondary" data-uri="{% url 'pybo:question_delete' question.id %}">
                                    삭제
                                </a>
                            </div>
                        {% endif %}

                        <!-- 질문댓글 시작! -->
                        {% if question.comment_set.count > 0 %}
                        <div class="mt-3">
                            {% for comment in question.comment_set.all %}
                                <a name="comment_{{ comment.id }}"></a>
                                <div class="comment py-2 text-muted">
                                    <span style="white-space: pre-line;">
                                        {{ comment.content }}
                                    </span>
                                    <span>
                                        -{{ comment.author }}, {{ comment.create_date }}
                                        {% if comment.modify_date %}
                                            (수정: {{ comment.modify_date }})
                                        {% endif %}
                                    </span>
                                    {% if request.user == comment.author %}
                                        <a href="{% url 'pybo:comment_modify_question' comment.id %}" class="small">
                                            수정
                                        </a>
                                        <a href="{% url 'pybo:comment_delete_question' comment.id %}" class="small">
                                            삭제
                                        </a>
                                    {% endif %}
                                </div>
                            {% endfor %}
                        </div>
                    {% endif %}
                    <div>
                        <a href="{% url 'pybo:comment_create_question' question.id %}" class="small">
                            <small>
                                댓글 추가 ..
                            </small>
                        </a>
                    </div>
                    <!-- 질문 댓글 끝! -->
                    
                    </div>
                </div>
            </div>
            <!-- 질문 끝! -->
        </div>
        <!-- 추천영역 꼬다리 끝 -->
        <h5 class="border-bottom my-3 py-2">
            {{ question.answer_set.count }}개의 답변이 있습니다.
        </h5>
        {% for answer in question.answer_set.all %}
            <a name="answer_{{ answer.id }}"></a>
            <div class="row my-3">
                <div class="col-1"> <!-- 추천 영역 -->
                    <div class="bg-light text-center p-3 boder font-weight-bolder md-1">
                        {{answer.voter.count}}
                    </div>
                    <a href="#" data-uri="{% url 'pybo:vote_answer' answer.id %}" class="recommend btn btn-sm btn-secondary btn-block my-1">
                        추천
                    </a>
                </div>
                <!-- 답변추천내용 끝이긴 한데 밑에 꼬다리 두개 추가-->
                <div class="col-11">
                    <div class="card">
                        <div class="card-body">
                            <div class="card-text">
                                {{ answer.content|mark }}
                            </div>
                            <div class="d-flex justify-content-end">
                                <!--수정일시(댓글) 표시 추가 시작-->
                                {% if answer.modify_date %}
                                    <div class="badge badge-light p-2 text-left mx-3">
                                        <div class="mb-2">
                                            modified at
                                        </div>
                                        <div>
                                            {{ answer.modify_date }}
                                        </div>
                                    </div>
                                {% endif %}
                                <!--수정일시 표시(댓글) 추가 시작-->
                                <div class="badge badge-light p-2 text-left">
                                    <div class="mb-2">
                                        {{ answer.author.username }}
                                    </div>
                                    <div>
                                        {{ answer.create_date }}
                                    </div>
                                </div>
                            </div>
                            {% if request.user == answer.author %}
                                <div class="my-3">
                                    <a href=" {% url 'pybo:answer_modify' answer.id %}" class="btn btn-sm btn-outline-secondary">
                                        수정
                                    </a>
                                    <a href="#" class="delete btn btn-sm btn-outline-secondary" data-uri="{% url 'pybo:answer_delete' answer.id %}">
                                        삭제
                                    </a>
                                </div>
                            {% endif %}


                            <!--답변댓글시작!-->
                            {% if answer.comment_set.count > 0 %}
                                <div class="mt-3">
                                    {% for comment in answer.comment_set.all %}
                                        <a name="comment_{{ comment.id }}"></a>
                                        <div class="comment py-2 text-muted">
                                            <span style="white-space: pre-line;">
                                                {{ comment.content }}
                                            </span>
                                            <span>
                                                -{{ comment.author }}, {{ comment.create_date }}
                                                {% if comment.modify_date %}
                                                    (수정: {{ comment.modify_date }})
                                                {% endif %}
                                            </span>
                                            {% if request.user == comment.author %}
                                                <a href="{% url 'pybo:comment_modify_answer' comment.id %}" class="small">
                                                    수정
                                                </a>
                                                <a href="#" class="small delete" data-uri="{% url 'pybo:comment_delete_answer' comment.id %}">
                                                    삭제
                                                </a>
                                            {% endif %}
                                        </div>
                                    {% endfor %}
                                </div>
                            {% endif %}
                            <div>
                                <a href="{% url 'pybo:comment_create_answer' answer.id %}" class="small">
                                    <small>
                                        댓글 추가..
                                    </small>
                                </a>
                            </div>
                            <!--답변댓글 끝!-->

                        </div>
                        
                    </div>
                </div>
            </div>
            {% endfor %}
            <form action="{%url 'pybo:answer_create' question.id %}" method="post" class="my-3">
                {% csrf_token %}
                {% if form.errors %}
                    <div class = "alert alert-danger" role="alert">
                        {% for field in form %}
                            {% if field.errors %}
                                <strong>
                                    {{ field.label }}
                                </strong>
                                {{ field.errors }}
                            {% endif %}
                        {% endfor %}
                    </div>
                {% endif %}
                <div class="form-group">
                    <textarea name="content" id="content"  
                            {% if not user.is_authenticated %}
                                disabled
                            {% endif %}
                        class="form-control" rows="10">
                    </textarea>
                </div>
                <input type="submit" value="답변등록" class="btn btn-primary"> 
            </form>
        </div>
{% endblock %}
{% block script %}
    <script type="text/javascript">
        $(document).ready(function() {

            $(".delete").on('click', function(){
                if(confirm("정말로 삭제하시겠습니까?")){
                    location.href = $(this).data('uri');
                }
            });
            $(".recommend").on('click', function(){
                if(confirm("정말로 추천하시겠습니까?")){
                    location.href = $(this).data('uri');
                }
            });
        });
    </script>
{% endblock %}

RESTART/templates/pybo/question_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">
        질문 등록
    </h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        <!-- 오류표시! -->
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
                {% for field in form %}
                    {% if field.errors %}
                    <strong>
                        {{ field.label}}
                    </strong>
                    {{ field.errors }}
                    {% endif %}
                {% endfor %}
            </div>
        {% endif %}
        <!-- 오류표시 끝!-->
        <div class="form-group">
            <label for="subject">
                제목
            </label>
            <input type="text" class="form-control" name="subject" id="subject" value="{{ form.subject.value|default_if_none:'' }}"><!--얘를 해주지 않으면 오류떴을때 none가 채워지거나 입력한 값이 날아갈수있다.-->
        </div>
        <div class="form-group">
            <label for="content">
                내용
            </label>
            <textarea class="form-control" name="content" id="content" rows="10">
                {{ form.content.value|default_if_none:'' }}
            </textarea>
        </div>
        <button type="submit" class="btn btn-primary">
            저장하기
        </button>
    </form>
</div>
{% endblock %}